### ISSUE TITLE
query regarding totient

### ISSUE THREAD

**Issue by d4rkvaibhav** [D1r3Wolf/CTF-writeups#1]
Can you explain a more in-depth about calculating the totient and how did it strike in your mind that you will take only the 3's power and exclude other primes?
And also why did you choose n = pow(3,1545) why not some other prime number in the n?

**Comment by D1r3Wolf** [comment]
we have big modules !
we know primes ,we can find the corresponding totient but It is also very big and the regarding Decryption key is also bigger 
as have have 
len(N) = 175366
len(C) = 175366
len(d) = 175366
M  = pow(C,d,N)
even though we know the values , calculation is impossible
But here the primes are repeating 
So there is an chance to construct a new modulus with that repetition
In all those primes 3 is smaller.
so that's why i have took 3 to construct new modulus 
as n = pow(3,1545) is smaller when compared to other numbers
now we calculate then totient for our modulus pow(3,1545) and calculate the regarding Decryption Key(d) it also small
now we can easily calculate pow(C,d,n) -> flag
